[book]
authors = ["dantezhu"]
language = "en"
src = "src"
title = "从技术到管理：可复制的职业发展之路"

[output.html]
additional-css = ["custom/custom.css"]

[output.html.print]
enable = false

# 依赖 HollowMan6/mdbook-pdf
# mdbook build
# [output.pdf]
